# ConvTasNet config
convtasnet:
  N: 256
  L: 20
  B: 256
  H: 512
  P: 3
  X: 10
  R: 4
  C: 2
  audio_channels: 2 #  stereo
  norm_type: gLN
  causal: False
  mask_nonlinear: 'relu'

# Training config
training:
  epochs: 200
  batch_size: 4       # Aggregate 2 iteration, effective batch size = 8
  num_workers: 4
  half_lr: yes
  early_stop: yes
  aggregate: 2        # aggregate gradiante every 2 iterations
# Optim config
optim:
  lr: 0.0005
# Data config
data:
  root: /path/to/MUSDB18
  mix_background: true
  segment: 5.0            # Seconds
  samples_per_track: 64
  sample_rate: 44100



